import jsPDF from 'jspdf';

export function generatePDF(patient, visits, prediction) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Header
  doc.setFillColor(15, 76, 129);
  doc.rect(0, 0, pageWidth, 35, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('NephroAlert', 15, 15);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('CKD Progression Report', 15, 23);
  doc.text(`Generated: ${new Date().toLocaleDateString('en-IN')}`, 15, 30);

  y = 45;
  doc.setTextColor(0, 0, 0);

  // Patient Info
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Patient Information', 15, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const info = [
    `Name: ${patient.fullName}`,
    `Age: ${patient.age} years | Gender: ${patient.gender}`,
    `Village: ${patient.village} | PHC: ${patient.phc}`,
    `Diabetes Duration: ${patient.diabetesDuration} years`,
    `Smoking: ${patient.smokingStatus ? 'Yes' : 'No'} | BP History: ${patient.bpHistory ? 'Yes' : 'No'}`,
  ];
  info.forEach(line => {
    doc.text(line, 15, y);
    y += 6;
  });

  y += 5;

  // Risk Assessment
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('AI Risk Assessment', 15, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  if (prediction) {
    doc.text(`Risk Score: ${prediction.score}/100`, 15, y); y += 6;
    doc.text(`Risk Level: ${prediction.level}`, 15, y); y += 6;
    doc.text(`Confidence: ${prediction.confidence}%`, 15, y); y += 6;
    y += 3;

    // Explanation - word wrap
    const explanation = prediction.explanation || '';
    const splitExplanation = doc.splitTextToSize(explanation, pageWidth - 30);
    doc.text(splitExplanation, 15, y);
    y += splitExplanation.length * 5 + 5;

    // Recommendation
    doc.setFont('helvetica', 'bold');
    doc.text('Recommendation:', 15, y); y += 6;
    doc.setFont('helvetica', 'normal');
    const splitRec = doc.splitTextToSize(prediction.recommendation || '', pageWidth - 30);
    doc.text(splitRec, 15, y);
    y += splitRec.length * 5 + 5;

    // Factors
    if (prediction.factors && prediction.factors.length > 0) {
      doc.setFont('helvetica', 'bold');
      doc.text('Key Risk Factors:', 15, y); y += 6;
      doc.setFont('helvetica', 'normal');
      prediction.factors.forEach(f => {
        doc.text(`  - ${f}`, 15, y); y += 5;
      });
      y += 5;
    }
  }

  // Check if we need a new page
  if (y > 200) {
    doc.addPage();
    y = 20;
  }

  // Visit History Table
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Visit History', 15, y);
  y += 8;

  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  const headers = ['Date', 'HbA1c', 'Creat.', 'eGFR', 'Urea', 'ACR', 'BP', 'Stage'];
  const colWidths = [28, 18, 18, 18, 18, 22, 28, 18];
  let x = 15;
  headers.forEach((h, i) => {
    doc.text(h, x, y);
    x += colWidths[i];
  });
  y += 5;

  doc.setFont('helvetica', 'normal');
  visits.forEach(visit => {
    if (y > 275) {
      doc.addPage();
      y = 20;
    }
    x = 15;
    const row = [
      new Date(visit.visitDate).toLocaleDateString('en-IN'),
      `${visit.hba1c}%`,
      `${visit.creatinine}`,
      `${visit.eGFR}`,
      `${visit.bloodUrea}`,
      `${visit.urineACR}`,
      `${visit.systolicBP}/${visit.diastolicBP}`,
      visit.ckdStageAtVisit ? `S${visit.ckdStageAtVisit}` : '-'
    ];
    row.forEach((cell, i) => {
      doc.text(cell, x, y);
      x += colWidths[i];
    });
    y += 5;
  });

  // Footer
  y = doc.internal.pageSize.getHeight() - 15;
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text('Generated by NephroAlert | ACS-AMRI Research Project | Dr. MGR Educational & Research Institute', 15, y);

  // Save
  doc.save(`patient_report_${patient._id}.pdf`);
}
